### ISSUE TITLE
Is the code available?

### ISSUE THREAD

**Issue by adrianlzt** [emiago/gophone#1]

**Comment by emiago** [comment]
Hi @adrianlzt except for media major part of code is on `sipgox` lib which wraps `sipgo`  for more functionality 

For now my focus is only there. 
Some parts I may export to `sipgox` as library/example. 

Pls also read this 
https://github.com/emiago/sipgox/issues/3#issuecomment-1807205843

What are you looking?

**Comment by adrianlzt** [comment]
Thanks for the info. I'm finally using python.
