### ISSUE TITLE
No source code for gophone

### ISSUE THREAD

**Issue by CompuRoot** [emiago/gophone#3]
Besides or compiled binary, do you plan to publish source code of `gophone`?

**Comment by emiago** [comment]
Hi @CompuRoot. I have no plans currently as my focus is more on libraries under hood, and no plans dedicating too much time on this tool, unless I really need. 

gophone is just utilizing `sipgox`  mainly. You can find it provide more info on libs. Of course current state is lot of experimenting, but I found gophone stable for use cases I had so far

**Comment by CompuRoot** [comment]
Got it, Thank you for explanation !
