### ISSUE TITLE
Error when installing on macOS: install.sh: line 19: syntax error near unexpected token `fi'

### ISSUE THREAD

**Issue by maik-parloa** [emiago/gophone#4]
The install script triggers the following error:
```
./install.sh: line 19: syntax error near unexpected token `fi'
```

There seems to be a `then` missing:
```bash
# Strange on mac this can be file
if [ -f $BIN_DIR ]; then
    echo "$BIN_DIR is file which should not happen."
    exit 1
fi 
```

**Comment by emiago** [comment]
Hi @maik-parloa thanks for opening issue. Yeah I did not find time yet for mac. Also signing is missing, so you may have this warnings as well. Feel free open issue for all findings

**Comment by maik-parloa** [comment]
@emiago Thank you for the quick response. Yes, signing actually is an additional issue, that prevents running gophone on company-secured device. I'm happy to open other issues I encounter as well 🙌 Thank you for your effort.

**Comment by emiago** [comment]
should be fixed in latest release
