### ISSUE TITLE
linux arm target?

### ISSUE THREAD

**Issue by itay-sho** [emiago/gophone#6]
hey, any chance you can release also a linux arm binary?

Thanks

**Comment by emiago** [comment]
sure. Only transcription may not work.

**Comment by emiago** [comment]
Hi @itay-sho I added a build. Can you please answer here, does build work for you. I was not able to test it.

**Comment by itay-sho** [comment]
Hey I tried to use the binary and I saw the following,
when I attempt to run the following (this is from the README):
```./gophone dial -ua alice -username=alice1234 -password=1234 "sip:echo@server:5060"```

I get the following:
```INF Dial > Fail to find any interface IP error="no interface found on system"```

and when I try the following:
```./gophone register -username=sipgo -password=1234 127.0.0.1:5060```

I get the following:
`18:13:07.353 FTL Target bad format error="invalid uri scheme"`

**Comment by emiago** [comment]
Hi @itay-sho , yeah I understand. 
First issue is weird, it could be something with permissions. 
Can you run it as root?

second I see it is mistake. Needs sip uri at end.  sip:127.0.0.1:5060. 
Mostly everything is sip uri.  Thanks for reporting

Yeah source may be avail at some point, just I want to keep focus libs. I use this tool daily, so it is tested from many scenarios.

**Comment by itay-sho** [comment]
Thanks, I will try with "sip" at first.

about the 1st issue, 
I ran it in a docker container.
tried once again using --net=host, didn't work as well but this time due:
```
18:25:43.262 ERR Dial > Call failed error="udp conn [fdc4:f303:9324::3]:55728 err. write udp [fdc4:f303:9324::3]:55728->185.45.152.174:5060: sendto: network is unreachable. transaction transport error"
```

I am not really sure what's the problem here, but I suspect that it takes an IPV6 dedicated interface and tries to use ipv4 and it didn't manage to route it.

third time I ran it on a VM directly (with a bridged interface), still didn't work with a similar log to the one above.

Might be useful to have an "interface" flag so that I could choose which one to use. 
If you would like to add it I would be grateful, and I would be glad to attempt to contribute in case that you'll decide to open source it.

Thank you

**Comment by emiago** [comment]
Hi @itay-sho .
Yes I think I already fixed this issue. Did not cathc the time to push fix. 

Anyway you can force interface with `-l 172.17.0.2:0`  
This is just listen (bind) to interface IP, this should skip this bug above. Anyway I will try to push fix this week.
